# Generated by Django 5.1.1 on 2024-09-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Crisis', max_length=100, null=True)),
                ('location', models.CharField(default='Unknown Location', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_id', models.CharField(max_length=100)),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.crisis')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('phon_number', models.CharField(max_length=20, null=True)),
                ('avprola_status', models.CharField(max_length=100, null=True)),
                ('crisis', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('task', models.CharField(max_length=255, null=True)),
                ('expense', models.CharField(max_length=255, null=True)),
                ('active_status', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
